import React from "react";
import { makeStyles, Grid, Box } from '@material-ui/core';
import section2img from "../assets/desktop-collabgraphic-E525152A-F8F0-4C56-8CF0-1924ABD97151.png";
import squirrelydan from "../assets/sqirl-2.png";
import auxicon from "../assets/actual-aux-logo.png";
import "../styles/About.css";

const useStyles = makeStyles({
    sec2img: {
        height: `84%`,
        width: `84%`
    },
    creatingPlaylists: {
        fontFamily: `'Prompt', sans-serif`,
        fontSize: `40px`,
        fontWeight: `200`,
        lineHeight: `50px`,
    },
    sec2container: {
        margin: `0 5vw`,
        minHeight: `100vh`,
    },
    body: {
        fontFamily: `Montserrat`,
        fontSize: `18px`
    },
    fullHeight: {
        // height: `100%`,
    },
    ourGoal: {
        fontFamily: `'Prompt', sans-serif`,
        fontSize: `40px`,
        fontWeight: `200`,
        lineHeight: `50px`,
        textAlign: `center`,
        margin: `0px`
    },
    goalBody: {
        fontFamily: `Montserrat`,
        fontSize: `18px`,
        textAlign: `center`,
    },
    swirlWrap:{
        marginTop: `3vw`,
        marginBottom: `3vw`,
        marginLeft: `-8vw`,
        width: `103vw`,
        marginRight: `-8vw`,
        overflow: `hidden`,
    },
    swirl: {
        textAlign: `center`,
        width: `105%`,
        height: `12vh`,
    },
    auxIcon: {
        position: `absolute`,
        top: `156vh`,
        left: `43vw`
    }
});

function FadeInSection(props) {
    const [isVisible, setVisible] = React.useState(false);
    const domRef = React.useRef();
    React.useEffect(() => {
        const observer = new IntersectionObserver(entries => {
            entries.forEach(entry => setVisible(entry.isIntersecting));
        });
        observer.observe(domRef.current);
    }, []);
    return (
        <div className={`fade-in-section-about ${isVisible ? 'is-visible-about' : ''}`} ref={domRef} >
            {props.children}
        </div>
    );
}

export default function About(props) {
    const classes = useStyles();
    return (
        <Grid item container id="1" className={classes.sec2container} >
            <Grid item container alignItems="flex-start">
                <Grid item md={4} className={classes.fullHeight}>
                    <FadeInSection>
                        <img src={section2img} className={classes.sec2img} />
                    </FadeInSection>
                </Grid>
                <Grid item md={8}>
                    <h4 className={classes.creatingPlaylists}>Manually creating playlists is now a thing of the past</h4>
                    <p className={classes.body}>Collaborative music is a bigger part of life than you’d think. Think of all the times you listen to music with others: car rides, date night, dinner parties, night clubs, even restaurants. You may not always realize it but in every case where music is playing, someone had to take the time to choose that music. Think of how convenient it would be to have a playlist generated by our powerful AI software with the click of a button rather than take time and manually collaborate on a playlist for your next…. anything!</p>
                </Grid>
            </Grid>
            <Grid item container direction="column">
                <Grid item>
                    <div className={classes.swirlWrap}>
                        <img src={squirrelydan} className={classes.swirl} />
                        <img src={auxicon} className={classes.auxIcon} height="127px" width="auto" />
                    </div>
                </Grid>
                <Grid item>
                    <h4 className={classes.ourGoal}>Our Goal</h4>
                    <Box mx={7}>
                        <p className={classes.goalBody}>We want to reinvent your daily collaborative music experience. Everything from your next event down to your daily drive with friends, Aux has you covered. Leave the hassle of music selection in the past with seamless, cross-platform group collaboration. At Aux, our mission is to provide our users with the tools necessary to make every group listening experience an Aux experience.</p>
                    </Box>
                </Grid>
            </Grid>
        </Grid>
    )
}